# Thông tin k\u1EBFt n\u1ED1i SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=ClassroomDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=YourStrong@Passw0rd

# C\u1EA5u hình \u0111\u1EC3 Hibernate t\u1EF1 ki\u1EC3m tra b\u1EA3ng trong SQL
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

